### ISSUE TITLE
Automatically set sort order for tokens based on position

### ISSUE THREAD

**Issue by marutypes** [arlosmolten/isometric-perspective#2]
My partner and I were trying this module out, and we noticed that the [sorting logic](https://github.com/arlosmolten/isometric-perspective/blob/main/scripts/betafeatures.js) is not currently being used, leading to things drawing in awkward ways like so:

![image](https://github.com/user-attachments/assets/81133cb1-49de-4843-82d6-8bf3d78a5c42)

I was able to fix the sort order code in `betafeatures,js` locally by switching up some of the APIs and using an X+Y algorithm to define the sort order of sprites, and didn't see any issues with performance from doing so. I can make a PR if you're interested.

**Comment by marutypes** [comment]
I'll run some tests with a lot of tokens, I confess to only having done a few at a time. If the performance with a lot of tokens is bad, it might be a worthwhile optional feature you can turn on with an appropriate warning, or maybe I can figure out why its a problem and mitigate it.

Either way, I plan to rebase on your newer changes and make a PR this week.

**Comment by arlosmolten** [comment]
Actually, I was trying to implement this feature today and found a version that I like, using the X+Y sort method that I didn't know about and you introduced me to. I think it's almost perfect, but unfortunately (for me) it breaks compatibility with the Token Ease module.

I'll release another pre-release version of the game and you can try it if you want. I'll still spend a few more days trying to figure out what's going on with the compatibility with the module.

**Comment by arlosmolten** [comment]
Added the feature in v0.5.0 beta.

**Comment by marutypes** [comment]
I'm still seeing the issue on my end with the release you made

https://github.com/user-attachments/assets/ce05b673-8144-4546-87cc-98b7e42fe6ac

with these settings
![image](https://github.com/user-attachments/assets/253f857d-8530-4915-b830-945f1e19c65c)

I'll take a look at the code and see how different it is from mine, maybe a PR will still be valuable.

**Comment by marutypes** [comment]
@arlosmolten The issue is actually that our X co-ordinate needs to be inverted to work properly. This is because what we think of as closer to the screen doesn't correspond to positive x, which means the X+Y is wrong without doing so.

I was able to get it working locally by changing the sort function like so:
```

function calculateTokenSortValue(token) {
  const dimensions = canvas.scene.dimensions;

  const { width, height } = dimensions;

  const tokenX = width - token.x;
  const tokenY = token.y;

  const sortValue = Math.round(((tokenX + tokenY) / (width + height)) * 10000);

  return sortValue;
}
```

and here is the result:

https://github.com/user-attachments/assets/17fd7ab9-d8c8-414e-a94b-7f12a382103a

I'll make a PR.
