### ISSUE TITLE
Horizontal Flip (on tokens) Doesn't Work With Iso Transformation

### ISSUE THREAD

**Issue by marutypes** [arlosmolten/isometric-perspective#3]
The option to horizontally flip token art currently doesn't work when they are transformed into isometric perspective. There is a special transformation [for *tiles* that is hooked up to the custom settings page on tiles for the module ](https://github.com/arlosmolten/isometric-perspective/blob/main/scripts/transform.js#L156) but nothing equivalent for tokens.

I can draw up a PR to apply the same type of transformation to tokens when their horizontal flip setting is set.

**Comment by arlosmolten** [comment]
I didn't implement this feature for tokens cause I didn't think it would be that useful. Usually you only want to flip tiles to avoid having to load multiples, but with tokens you usually keep the same position and only change it with macros.

I'm not opposed to doing the feature but maybe it would be better to put it as a macro on a compendium to be used on demand.

**Comment by arlosmolten** [comment]
Hi. I'm just posting here cause my latest pre-release changed some things and the token config screen now works with isometric, and then the flip token feature too.

**Comment by marutypes** [comment]
So this does work on the beta tag, but it does seem to turn off the `offset` fields in the isometric tab. I suppose they aren't super necessary anymore however now that the pivot settings work in iso mode.

Part of me wonders if it would be better to have separate offsets for iso and non-iso modes so that you can easily switch between scenes that have it enabled and disabled, but that's a separate issue I suppose.

**Comment by arlosmolten** [comment]
Yes, I haven't removed these parts of the isometric tab yet so that anyone who updates will have a way to change the values, mainly isometric scale. The offset value will still be applied to the token flag, but it will no longer be relevant. (In fact, I should find a way to change this in a more efficient way...)

I also feel that having the isometric functionality separately would be nice, but then I would have to replicate (almost) all of the controls, like I did with offset and scale. Plus, we already had to use some of the controls from the Appearance tab, like image path and dimensions.

**Comment by marutypes** [comment]
> I also feel that having the isometric functionality separately would be nice, but then I would have to replicate (almost) all of the controls, like I did with offset and scale. Plus, we already had to use some of the controls from the Appearance tab, like image path and dimensions

That's true... maybe its better to just use as many of the built-in controls as possible so that it works cleanly with something like the "token variants" module.

I do wonder if maybe the iso transformation on tokens should be overridden when you turn it off on the scene level though. 🤔

**Comment by arlosmolten** [comment]
> maybe the iso transformation on tokens should be overridden when you turn it off on the scene level though

This is something I've said before to myself I needed to fix and I forgot entirely. This isn't even something hard to do... I'll push this fix on next update.

**Comment by arlosmolten** [comment]
In the last update I've reverted the control scheme to my isometric tab, cause it was causing too much issues, and with this I've implemented your last request.

I'll close this issue, cause I finnaly fix the flip token feature. If you want to discuss anything else, I've created a discord server, and the link is on README.
